name: CI/CD - Docker + Railway

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/taskmanager-api:latest

    - name: Install Railway CLI
      run: npm install -g railway

      # 🚀 Deploy to Railway
    - name: 🚀 Redeploy on Railway
      run: railway up --service=taskmanager-api --ci
      env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}